# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('BetId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamId', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30, null=True, unique=True)),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('sport', models.CharField(max_length=30, null=True)),
                ('number_of_players', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_1',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('birthday', models.DateField(blank=True)),
                ('passport', models.PositiveIntegerField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_1'),
        ),
    ]
